### ISSUE TITLE
I can't upload files

### ISSUE THREAD

**Issue by joker314** [ScratchModStocksAPI/Stocks-Mod#1]
It says I need push access

**Comment by BKFighter** [comment]
@joker314 I gave you some accessy thingy. Hopefully that's what you needed.

**Comment by joker314** [comment]
Thx
I'll try

**Comment by BKFighter** [comment]
Looks like you got it.

**Comment by joker314** [comment]
Don't we need to include Scratch's licence?

**Comment by joker314** [comment]
Yeah I did it. I' struggling to create a folder
